# Generated by Django 3.1 on 2020-08-19 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_follower_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='relation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 4, 19, 3, 188449)),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 4, 19, 3, 188449)),
        ),
    ]
