# Generated by Django 3.1 on 2020-08-25 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200820_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='relation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 7, 18, 53, 443682)),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 7, 18, 53, 444678)),
        ),
    ]
