# Generated by Django 3.1 on 2020-08-25 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200825_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='relation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 8, 20, 33, 861159)),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 8, 20, 33, 861159)),
        ),
    ]
