# Generated by Django 3.1 on 2020-08-25 01:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='blogs/%Y/%m/')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2020, 8, 25, 1, 48, 53, 445637, tzinfo=utc))),
                ('likes', models.ManyToManyField(related_name='user_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
